version: "3.8"
services:
  tokenizer:
    image: 192.168.239.161:5000/2407/tokenizer:1.0.0
    environment:
      PORT: 3002
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: start-first
    command: ["sh","-c","nuxt --port 3002 --module tokenizer.py --workers 2"]
  keywords:
    image: 192.168.239.161:5000/2407/keywords-filter:1.0.0
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: start-first
    healthcheck:
      test: ["CMD","grpc_health_probe","-addr=:50051"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 1s
    configs:
      - source: 2407-keywords-conf
        target: /app/config.yaml
      - source: 2407-keywords-dict
        target: /app/dict.txt
    entrypoint: ["./keywords-filter"]
    command: ["--config=config.yaml","--dict=dict.txt"]
  sensitive:
    image: 192.168.239.161:5000/2407/keywords-filter:1.0.0
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: start-first
    healthcheck:
      test: [ "CMD","grpc_health_probe","-addr=:50051" ]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 1s
    configs:
      - source: 2407-sensitive-conf
        target: /app/config.yaml
      - source: 2407-sensitive-dict
        target: /app/dict.txt
    entrypoint: [ "./keywords-filter" ]
    command: [ "--config=config.yaml","--dict=dict.txt" ]
  ai-chat-service:
    image: 192.168.239.161:5000/2407/ai-chat-service:1.0.0
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: start-first
    healthcheck:
      test: [ "CMD","grpc_health_probe","-addr=:50051" ]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 1s
    configs:
      - source: 2407-ai-chat-service-conf
        target: /app/config.yaml
  ai-chat-backend:
    image: 192.168.239.161:5000/2407/ai-chat-backend:1.0.0
    ports:
      - "7080:80"
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: start-first
    healthcheck:
      test: [ "CMD","curl","http://localhost/api/health" ]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 1s
    configs:
      - source: 2407-ai-chat-backend-conf
        target: /app/config.yaml
configs:
  2407-keywords-conf:
    file: ./configs/keywords.yaml
  2407-keywords-dict:
    file: ./configs/keyword-dict.txt
  2407-sensitive-conf:
    file: ./configs/sensitive.yaml
  2407-sensitive-dict:
    file: ./configs/sensitive-dict.txt
  2407-ai-chat-service-conf:
    file: ./configs/ai_chat_service.yaml
  2407-ai-chat-backend-conf:
    file: ./configs/ai_chat_backend.yaml